name: ios_background_uploader
description: A Flutter plugin for uploading large files in the background on iOS with progress updates.
version: 0.0.2
homepage: https://github.com/Sagar-Shrivastava/ios_background_uploader
repository: https://github.com/Sagar-Shrivastava/ios_background_uploader
issue_tracker: https://github.com/Sagar-Shrivastava/ios_background_uploader/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosBackgroundUploaderPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
